# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.46.1"

default_platform :ios


platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
    cocoapods
    # increment_build_number
    # xctool # run the tests of your app
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    cert(output_path: "./fastlane/certificate")
    sigh(force: true, output_path: "./fastlane/provision")
    gym(scheme: "WaniKani", output_directory: "./fastlane/build")
    pilot(skip_submission: true)
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    frameit(silver: true)
    deliver(force: true)
  end

  after_all do |lane|
    
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
