
# snapshot --reinstall_app
# snapshot reset_simulators

devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s"
])

languages([
  "en-US"
])

workspace "../WaniKani.xcworkspace"
scheme "WaniKani"
app_identifier "com.haawa.WaniKani"
