
reinstall_app true
# snapshot reset_simulators

devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s"
])

languages([
  "en-US"
])

workspace "/Users/haawa799/Google\ Drive/IOS\ Projects/WaniKani/WaniKani.xcworkspace"
scheme "WaniKani"
app_identifier "com.haawa.WaniKani"
